comment test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,30 +35,30 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  test-installation:
-    needs: build
-    strategy:
-      matrix:
-        os:
-          - ubuntu-latest
-          - ubuntu-24.04-arm
-          - macos-latest
-          - macos-13
-          - windows-latest
-      fail-fast: false
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Download and install
-        run: |
-          curl -sL https://get.sitedog.io | sh
+  # test-installation:
+  #   needs: build
+  #   strategy:
+  #     matrix:
+  #       os:
+  #         - ubuntu-latest
+  #         - ubuntu-24.04-arm
+  #         - macos-latest
+  #         - macos-13
+  #         - windows-latest
+  #     fail-fast: false
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - name: Download and install
+  #       run: |
+  #         curl -sL https://get.sitedog.io | sh
           
-      - name: Check binary version
-        run: |
-          sitedog version
-          # Check that version matches the tag
-          VERSION=$(sitedog version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
-          if [ "$VERSION" != "$TAG_VERSION" ]; then
-            echo "Version mismatch: binary version $VERSION != tag version $TAG_VERSION"
-            exit 1
-          fi
+  #     - name: Check binary version
+  #       run: |
+  #         sitedog version
+  #         # Check that version matches the tag
+  #         VERSION=$(sitedog version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+  #         TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
+  #         if [ "$VERSION" != "$TAG_VERSION" ]; then
+  #           echo "Version mismatch: binary version $VERSION != tag version $TAG_VERSION"
+  #           exit 1
+  #         fi
